<!-- Modal -->
<div class="modal fade" id="upModal" role="dialog">
<div class="modal-dialog">

<!-- Modal content-->
<div class="modal-content">
<div class="modal-header">
<h5 class="modal-title">Upload File</h5>
<button type="button" class="close" data-dismiss="modal">&times;</button>
</div>
<div class="modal-body">
<ul id="filelist"></ul>
<br />
 
<div id="container">
    <a id="browse" href="javascript:;">[Browse...]</a>
    <a id="start-upload" href="javascript:;">[Start Upload]</a>
</div>
 
<br />
<pre id="console"></pre>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>
</div>

</div>
</div>

<footer class="footer footer-black  footer-white ">
<div class="container-fluid">
<div class="row">
<nav class="footer-nav">
<ul>
<li>
<a href="#" target="_blank"></a>
</li>
<li>
<a href="#" target="_blank"></a>
</li>
<li>
<a href="#" target="_blank"></a>
</li>
</ul>
</nav>
<div class="credits ml-auto">
<span class="copyright">
©
<script>
document.write(new Date().getFullYear())
</script>, made with <i class="fa fa-heart heart"></i> by CHDD
</span>
</div>
</div>
</div>
</footer>
</div>
</div>
<!--   Core JS Files   -->
<script src="../assets/js/jquery.min.js"></script>
<script src="../assets/js/popper.min.js"></script>
<script src="../assets/js/bootstrap.min.js"></script>
<script src="../assets/js/perfect-scrollbar.jquery.min.js"></script>
<!-- Chart JS -->
<script src="../assets/js/chartjs.min.js"></script>
<!--  Notifications Plugin    -->
<script src="../assets/js/bootstrap-notify.js"></script>
<!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
<script src="../assets/js/paper-dashboard.min.js?v=2.0.0" type="text/javascript"></script>
<script src="../assets/js/dash.js"></script>
<!--  Plupupload Plugin    -->
<script type="text/javascript" src="../assets/js/plupload.full.min.js"></script>
<script src="../assets/js/main.js"></script>
</body>

</html>